name: GenerationXM
favicon: null
layout_spectrum: 0.10201742593199015
typography_spectrum: 0.5440342635847628
title: Music and more - GenerationXM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#14100f'
    - '#f4cf42'
    - '#b48101'
    - '#d6d7d9'
    - '#3c3a3b'
  brandStrength: 0.2958587564062327
  lightness: 0.5991831459105015
  saturation: 0.322276666527614
  rhythmicContrast: 0.9100819092709571
purpose: []
