typography_spectrum: 0.5440342635847628
color:
  brandColors:
    - '#14100f'
    - '#f4cf42'
    - '#b48101'
    - '#d6d7d9'
    - '#3c3a3b'
  brandStrength: 0.2958587564062327
  lightness: 0.5991831459105015
  saturation: 0.322276666527614
  rhythmicContrast: 0.9100819092709571
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.10201742593199015
analytics:
  google: null
  facebook: null
  twitter: null
name: GenerationXM
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: GenerationXM
description: Music and more...
purpose: []
